name: expandable_bottom_bar_new
description: Animatable bottom app bar with expandable sheet. Use me if you need cool bottom bar!
homepage: https://github.com/VrajGohil/expandable-bottom-bar

version: 2.0.0-nullsafety.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
